version: "3"

services:
  app:
    restart: unless-stopped
    image: gei
    volumes:
      - ./log:/log
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gei.rule=Host(`pyyin-gei.im.ncnu.edu.tw`)"
      - "traefik.http.routers.gei.entrypoints=websecure"
      - "traefik.http.routers.gei.service=gei-server"
      - "traefik.http.services.gei-server.loadbalancer.passhostheader=true"
      - "traefik.http.services.gei-server.loadbalancer.server.port=8085"
      - "traefik.docker.network=traefik_network"
networks:
  traefik_network:
    external: true